//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba4
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using vjezba4.ViewModel;

    public partial class Patient : ViewModelBase
    {
        public string Oib { get; set; }
        public string Mbo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string MedicalDiagnosis { get; set; }
        public string Insurance { get; set; }
        public string Status { get; set; }

        private ObservableCollection<Patient> _patientRecords;
        public ObservableCollection<Patient> PatientRecords
        {
            get
            {
                return _patientRecords;
            }
            set
            {
                _patientRecords = value;
                OnPropertyChanged("PatientRecords");
            }
        }

        private void StudentModels_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            OnPropertyChanged("PatientRecords");
        }
    }
}
